### ISSUE TITLE
Manual install process does not apply cassandra schemas

### ISSUE THREAD

**Issue by mbt-msw** [Metaswitch/homestead#235] opened 2015-07-06 13:51 UTC
Performing a manual install as described in [the manual install doc](http://clearwater.readthedocs.org/en/latest/Manual_Install/index.html).

I installed `clearwater-cassandra`, `homestead`, `homestead-prov`, and then `clearwater-management`.  After that I set up `/etc/clearwater/shared_config`.

However, homestead and homestead-prov aren't running properly, and their cassandra schemas have not been created.

Running `/usr/share/clearwater/cassandra-schemas/homestead_cache.sh` and `/usr/share/clearwater/cassandra-schemas/homestead_provisioning.sh` manually and then restarting homestead and homestead-prov fixes the issue.

It looks like the homestead (etc.) postinst scripts are bailing with this:
```
xdms_hostname is not defined
hs_provisioning_hostname is not defined
No hs_hostname set in /etc/clearwater/shared_config
```

But at that point we haven't set up `/etc/clearwater/shared_config`, so that's not surprising.

**Comment by mirw** [comment] 2015-07-15 14:11
Marking as high priority until we understand this - it's pretty serious if no-one can install Clearwater using the manual process.

**Comment by rkd-msw** [comment] 2015-07-15 14:13
@bossmc, won't the restart of clearwater-infrastructure when installing shared config also run /usr/share/clearwater/cassandra-schemas/*?

**Comment by bossmc** [comment] 2015-07-15 15:09
Don't think so.  I think the issue is that the `postinst` script calls the `clearwater-infrastructure` scripts manually (rather than asking `clearwater-infrastructure` to run them for us).  This means that, if they fail we fail (`set -e`) and don't go on to configure the schemas.

Elsewhere we simply `service clearwater-infrastructure restart` which swallows failures and allows the `postinst` to continue.

**Comment by eleanor-merry** [comment] 2015-08-28 16:25
The various postinst scripts errors have been fixed in the PRs referenced in https://github.com/Metaswitch/crest/pull/229

The cassandra schemas will get re-run as part of clustering, and on `service clearwater-infrastructure restart`

**Closed by eleanor-merry** 2015-08-28 16:25 UTC
Labels: bug, high-priority
