### ISSUE TITLE
Homestead appears to be checking the wrong returncode in SAAs

### ISSUE THREAD

**Issue by steelyvoid** [Metaswitch/homestead#359] opened 2016-07-05 14:00 UTC
While reviewing my recent refactoring of ImpuRegDataTask::on_sar_response (https://github.com/Metaswitch/homestead/blob/dev/src/handlers.cpp#L1685), @AlexHockey spotted that this routine is checking the result_code against '5001' to determine whether to propagate the error as an HTTP 404 or 500.

We think that this is doing the wrong check.  A result code of '5001' is 'DIAMETER_AVP_UNSUPPORTED'.  Could it be that we should be matching against the _experimental_ result code (for which a value of '5001' means 'DIAMETER_ERROR_USER_UNKNOWN')?

**Comment by graemerobertson** [comment] 2016-07-05 14:25
I think this is essentially a duplicate of https://github.com/Metaswitch/homestead/issues/306 - @steelyvoid, do you agree?

**Comment by steelyvoid** [comment] 2016-07-05 14:39
Its in the same area, though I don't think #306 makes the point that the code is checking the result code as if it was the experimental code and potentially reporting the wrong HTTP code as a result

Note that the recent refactoring I did means that part of #306 ("However, we should, at the very least, accurately extract and log the result code.") is now fixed by https://github.com/Metaswitch/homestead/pull/354

**Comment by richardwhiuk** [comment] 2016-09-06 15:36
This also applies to MAA responses.

**Comment by richardwhiuk** [comment] 2016-09-12 10:59
Steve, this is fixed in the Sprint Missingno Release that we are about to cut.

**Closed by richardwhiuk** 2016-09-12 10:59 UTC
Labels: bug, medium-priority
