### ISSUE TITLE
Homestead crashed when changing DNS records and restarting processes

### ISSUE THREAD

**Issue by AME2** [Metaswitch/homestead#406] opened 2016-12-20 16:13 UTC
During some resiliency testing I was experimenting with using two different HSSs. I had my hss_realm configured as ame22.clearwater.test and changed my DNS entries from:

hss-1.ame22.clearwater.test | A | 8.8.8.8
hss-2.ame22.clearwater.test | A | 10.225.166.10

to:

hss-1.ame22.clearwater.test | A | 10.225.166.10
hss-2.ame22.clearwater.test | A | 8.8.8.8

after I did this on Homestead I restarted clearwater-infrastructure and the homestead process.

#### Symptoms
This caused Homestead to crash and I was unable to register subscribers. I've attached the log and a couple of diagnostic bundles from the time of the crash. Unfortuately I have tried following the above procedure and have been unable to reproduce this bug.
[homestead_20161220T140000Z.txt](https://github.com/Metaswitch/homestead/files/664165/homestead_20161220T140000Z.txt)
[20161220143800Z.ame22-homestead-1.ame22.clearwater.test.homestead.tar.gz](https://github.com/Metaswitch/homestead/files/664166/20161220143800Z.ame22-homestead-1.ame22.clearwater.test.homestead.tar.gz)
[20161220143707Z.ame22-homestead-1.ame22.clearwater.test.homestead.tar.gz](https://github.com/Metaswitch/homestead/files/664167/20161220143707Z.ame22-homestead-1.ame22.clearwater.test.homestead.tar.gz)

#### Impact
This was preventing me from registering subscribers, however after this happened I restarted the homestead process and everything seemed to go back in to a nice state where I could make successful registrations.

#### Release and environment 
2 Sprouts: 10.0.0-161216-~255.00.0
2 Homesteads: 10.0.0-161216-~255.00.0
1 Ralf: 10.0.0-161216-~255.00.0
1 real external HSS

#### Steps to reproduce
Create a deployment as above. Configure DNS records as above. Restart the clearwater-infrastructure and homestead processes on the Homestead node. Change the DNS records as above and restart the processes again.

**Comment by graemerobertson** [comment] 2016-12-20 16:18
`_diameter._tcp.ame22.clearwater.test` resolved only to `hss-1.ame22.clearwater.test` so it might well be relevant that we were switching between having an HSS configured and not having an HSS configured. Since this is a crash, we should at the very least investigate it so I'm going to make this critical.

**Comment by chris-elford-metaswitch** [comment] 2017-01-24 11:20
I'd like to at least understand what these are.

**Comment by graemerobertson** [comment] 2017-02-03 20:47
I don't believe there is an issue here.
* I don't think Homestead did crash.
* It looked like it was possibly killed by monit immediately after receiving a termination signal, which is odd, but this happened whilst processes were being started and I think it's going to be difficult to figure out exactly what happened...
* I'm going to get a second opinion on this, particularly with the monit logs, and also discuss with @AME2, but my expectation is that we can close this.

**Comment by graemerobertson** [comment] 2017-02-07 18:14
My previous comment is complete rubbish - I'm not sure how I came to that conclusion; I must have been looking at the wrong log file.

I think this is actually https://github.com/Metaswitch/homestead/issues/399 with traffic going through through the Homestead node.

**Comment by graemerobertson** [comment] 2017-02-10 11:35
I'm closing this issue because it's basically a duplicate of https://github.com/Metaswitch/homestead/issues/399 and I've fixed the main difference between the two issues (i.e. the crashes), and I'm going to pass the other issue back to RKD for re-test.

@AME2 feel free to re-test or re-open or whatever you like if you disagree.

**Closed by graemerobertson** 2017-02-10 11:35 UTC
Labels: bug, cat:stability, cat:system-test, critical, high-priority, major
